### PR TITLE
Visual fix for icon on Linux and Windows & fix error with folder selection

### PR DESCRIPTION
**Pull request by anirudhb**
This pull request will change the icon to be white (by default) on Linux and Windows because it looks better, in my opinion. Don't merge unless I've uploaded the white icon. Also, this removes the 1x version of the black icon because it is not needed. I have also added a commit which will prevent the "Internal Errror" dialog when the user presses "Cancel" on the folder selection window.

### CODE REVIEW

**Comment by anirudhb** [comment]
@sindresorhus Could you please put the white icon inside the app folder?

**Comment by sindresorhus** [comment]
> Also, this removes the 1x version of the black icon because it is not needed.

It's needed for non-retina screens.

**Comment by sindresorhus** [comment]
I went with a colored icon instead for Linux and Windows.

**Comment by anirudhb** [comment]
@sindresorhus It works fine for non-retina screens.

**Comment by anirudhb** [comment]
@sindresorhus And by colored, you mean white?

**Comment by sindresorhus** [comment]
@anirudhb Yes, but it's not guaranteed to work perfectly. Each OS resizes the image differently and might do a bad job at it (Windows especially). Better to just have them.

**Comment by anirudhb** [comment]
@sindresorhus You forgot to add my other change to the code: prevent the "error" dialog when the user clicks "Cancel" in the folder selection dialog. :stuck_out_tongue:

**Comment by sindresorhus** [comment]
@anirudhb Oh missed that. Your fix was not entirely correct though, so I did a separate commit.

**Pull request closed without merging**
